### ISSUE TITLE
Command line problem

### ISSUE THREAD

**Issue by wenbostar** [wenbostar/PDV#3]
System: Linux
java -jar PDV-1.0.0.jar --help
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at PDVCLI.PDVCLIMainClass.<init>(PDVCLIMainClass.java:173)
	at PDVGUI.gui.PDVMainClass.main(PDVMainClass.java:247)

**Comment by wenbostar** [comment]
In Linux system, PDV requires  X11 environment to automatically generate figures.

**Comment by Kirovez** [comment]
Is it possible to run ONE PSM mode under command line? I need to generate graph using single spectrum .mgf file and .txt file with single peptide.

**Comment by wenbostar** [comment]
Yes, it's possible. You can take a look at the section "4 Using PDV in command line mode" in the PDV user manual: [PDV user's manual](http://pdv.zhang-lab.org/data/download/PDV-Manual.pdf). But I recommend you to use the GUI if you only want to visualize one PSM.
