### ISSUE TITLE
PDV txt format input

### ISSUE THREAD

**Issue by wenbostar** [wenbostar/PDV#48]
Exception in thread "DisplayThread" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at PDVGUI.fileimport.TextFileImport.parseTextFile(TextFileImport.java:252)
	at PDVGUI.fileimport.TextFileImport.access$100(TextFileImport.java:30)
	at PDVGUI.fileimport.TextFileImport$1.run(TextFileImport.java:141)

**Comment by wenbostar** [comment]
This was fixed in v1.8.0.
