### ISSUE TITLE
PDV txt format input

### ISSUE THREAD

**Issue by wenbostar** [wenbostar/PDV#49]
![image](https://user-images.githubusercontent.com/5302110/234159170-276de2a1-abcf-484f-8f01-53f1c49ebea7.png)

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at PDVGUI.gui.utils.SpectrumMainPanel.updateSpectrum(SpectrumMainPanel.java:1477)
	at PDVGUI.gui.utils.SpectrumMainPanel.updateSpectrum(SpectrumMainPanel.java:2011)
	at PDVGUI.gui.PDVMainClass.updateSpectrum(PDVMainClass.java:3786)
	at PDVGUI.gui.PDVMainClass.spectrumJTableKeyReleased(PDVMainClass.java:3230)
	at PDVGUI.gui.PDVMainClass.access$400(PDVMainClass.java:57)
	at PDVGUI.gui.PDVMainClass$5.keyReleased(PDVMainClass.java:869)
	at java.desktop/java.awt.AWTEventMulticaster.keyReleased(Unknown Source)
	at java.desktop/java.awt.Component.processKeyEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException

**Comment by wenbostar** [comment]
![image](https://user-images.githubusercontent.com/5302110/234159842-2e8f1a52-aca2-44b8-b9dc-88f3a159d727.png)

**Comment by wenbostar** [comment]
This was fixed in v1.8.0.
