### ISSUE TITLE
how to visualize maxquant results by using PDV command line ?

### ISSUE THREAD

**Issue by BiGump123** [wenbostar/PDV#51]
my command:
java -jar /share/liuqi/ganyuli/proteome/software/PDV-1.7.4/PDV-1.7.4.jar \
-r combined \
-rt 5 \
-s . \
-st 1 \
-i tab2.txt \
-k s \
-o output \
-a 0.5 \
-c 5 \
-pw 1 \
-fw 800 \
-fh 400 \
-fu px \
-ft **pdf**
Possibly, I didn't set the corret input data format, so always appeared this error when I used the command line for **visualizing maxquant results**:
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at PDVCLI.MaxQuantImport.parseParameters(MaxQuantImport.java:1024)
        at PDVCLI.MaxQuantImport.<init>(MaxQuantImport.java:162)
        at PDVCLI.PDVCLIMainClass.importFile(PDVCLIMainClass.java:669)
        at PDVCLI.PDVCLIMainClass.runCMD(PDVCLIMainClass.java:389)
        at PDVCLI.PDVCLIMainClass.<init>(PDVCLIMainClass.java:229)
        at PDVGUI.gui.PDVMainClass.main(PDVMainClass.java:282)

So what is the correct input data format for **visualizing maxquant results** by command line?

**Comment by wenbostar** [comment]
Do you want to generate figures for all spectra or just some spectra using command line?

**Comment by KaiLiCn** [comment]
Hi, 

First, please copy the parameter file `"mqpar.xml"` into the combined folder (the reason causing this error). You could put all interested pure peptide sequences in your "tab2.txt" and set `-k p`. PDV will output all PSMs with the peptide sequence you input. Other parameters look good to me.

Please let me know if it still doesn't work.

Kai

**Comment by BiGump123** [comment]
Dear Kai,

Thank you very very very much! After I moved the mqpar.xml into the combined folder, than it did work! The figures sucessfully generated finally. Next, I would try to  generate figures for a large scale spectra by using command line.

best wishes!

Yuli Gan

**Comment by BiGump123** [comment]
Dear wenbostar, 
Sincerely Thanks for your reply! I want to generate figures for my interested peptide sequences, and Kai's opinion helped me. Next, I would try to generate figures for a large scale spectra by using command line. If there were problems, I would touch you again. In addtion, If the PDV mannual updated, containing kai's opinions for command line, that would be perfect for using PDV command line! 

best wishes !

Yuli Gan

**Comment by BiGump123** [comment]
Come back for help again!

My command:
java -jar /data2/users/ganyuli/proteome/software/PDV-1.7.4/PDV-1.7.4.jar \
> -r combined \
> -rt 5 \
> -s . \
> -st 1 \
> -i scan_number.txt \
> -k s \
> -o peptide \
> -a 0.5 \
> -c 5 \
> -pw 1 \
> -fw 800 \
> -fh 400 \
> -fu px \
> -ft pdf

The error: Spectrum 'RawFile: P16186-11 Index: 20198 Charge: 3' in mgf file 'P16186-11.mgf' not found

The PDV will generate the mgf file, I don't know why there is no 'RawFile: P16186-11 Index: 20198 Charge: 3'. I think the PDV should generate all the Index number,is the reason that the combined folder had been fixed or I used  new maxquant version(2.4.11)?

Need your help!
Thank you!


SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data2/users/ganyuli/proteome/software/PDV-1.7.4/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data2/users/ganyuli/proteome/software/PDV-1.7.4/lib/logback-classic-1.1.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
P16186-11 = 17289
java.io.IOException: Spectrum 'RawFile: P16186-11 Index: 20198 Charge: 3' in mgf file 'P16186-11.mgf' not found.
        at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getPrecursor(SpectrumFactory.java:633)
        at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getPrecursor(SpectrumFactory.java:293)
        at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getPrecursor(SpectrumFactory.java:261)
        at PDVCLI.MaxQuantImport.parseResults(MaxQuantImport.java:736)
        at PDVCLI.MaxQuantImport.addAllSpectrumFiles(MaxQuantImport.java:623)
        at PDVCLI.MaxQuantImport.generateNewMGFFile(MaxQuantImport.java:579)
        at PDVCLI.MaxQuantImport.<init>(MaxQuantImport.java:174)
        at PDVCLI.PDVCLIMainClass.importFile(PDVCLIMainClass.java:669)
        at PDVCLI.PDVCLIMainClass.runCMD(PDVCLIMainClass.java:389)
        at PDVCLI.PDVCLIMainClass.<init>(PDVCLIMainClass.java:229)
        at PDVGUI.gui.PDVMainClass.main(PDVMainClass.java:282)
