### ISSUE TITLE
Exception in thread "DisplayThread" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Yck711** [wenbostar/PDV#60]
Hi,

I have encountered an issue when i check the spectrum of file generated from MaxQuant. The log is following:

Wed Aug 23 11:39:23 CST 2023: PDV-1.8.1
The local country is CN
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/Tools/Others/PDV-1.8.1/PDV-1.8.1/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/Tools/Others/PDV-1.8.1/PDV-1.8.1/lib/logback-classic-1.1.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "DisplayThread" java.lang.NullPointerException
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at PDVGUI.fileimport.MaxQuantFileImport.getAllSpectrumRT(MaxQuantFileImport.java:292)
	at PDVGUI.gui.PDVMainClass$21.run(PDVMainClass.java:2143)

And there is no issues was reported when i use the test data on the github
Thank you

**Comment by Yck711** [comment]
> It's likely due to MaxQuant version issue. Which version of MaxQuant are you using?
The version of MaxQuant is v2.0.1.0

**Comment by KaiLiCn** [comment]
Sorry, I still need some time to test the new MaxQuant results.
