### ISSUE TITLE
FragPipe/DIA-Umpire

### ISSUE THREAD

**Issue by wenbostar** [wenbostar/PDV#63]
When I loaded the psm.tsv and mzML files generated from FragPipe/DIA-Umpire into PDV, I got the following error:

```
java.lang.NullPointerException
	at PDVGUI.fileimport.FragePipeImport.getSpectrum(FragePipeImport.java:766)
	at PDVGUI.fileimport.FragePipeImport.parseResultMzML(FragePipeImport.java:316)
	at PDVGUI.fileimport.FragePipeImport.access$000(FragePipeImport.java:42)
	at PDVGUI.fileimport.FragePipeImport$1.run(FragePipeImport.java:159)

```

**Comment by KaiLiCn** [comment]
Hi Bo,

Did you try to open the result directly inside the FragPipe? Can you share your psm.tsv and mzML file with me?

Kai
